services:
  db:
    image: postgres:latest
    container_name: db_chat_dev
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
    - 5431:5432
    volumes:
    - pg_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment: 
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports: 
      - 5430:80
    depends_on:
      - db
  
  backend:
    build: . 
    container_name: backend_chat
    env_file:
      - .env.production 
    ports:
      - "8888:8000"  
    depends_on:
      - db  
    volumes:
      - ./app:/app/app

volumes:
  pg_data:
